import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { MenubarComponent } from "@/components/menu";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  left,
  right,
}: Readonly<{
  left: React.ReactNode;
  right: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MenubarComponent />
          <div className="h-[calc(100vh-40px)]">
            <ResizablePanelGroup direction="horizontal" className="border">
              <ResizablePanel defaultSize={25}>{left}</ResizablePanel>
              <ResizableHandle />
              <ResizablePanel defaultSize={75}>{right}</ResizablePanel>
            </ResizablePanelGroup>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
